# Main reference FASTA
main_fasta: "FungiDB-65_CneoformansH99_Genome.fasta" 

# Main reference GFF
main_gff: "FungiDB-65_CneoformansH99.gff" 

# Directory name with the sub references FASTA files
subref_directory: "sub_references/" 


# Specifies the set of features to be lifted over
feature_file: "features.txt"

threads_liftoff: 4