# This is the profile configuration file for SLURM execution.

# To run the workflow in SLURM use the following command:
# snakemake --profile config/slurm

executor: slurm
default-resources:
  slurm_partition: # Partition to submit jobs to
  slurm_account: # Account
  mem_mb_per_cpu: 1000
  nodes: 1
  cpus_per_task: 12
  runtime: 2880
  tmpdir: "'temp/'"

# Config you can change
jobs: 100
keep-going: False
rerun-incomplete: True
printshellcmds: True
dry-run: False
conda-frontend: mamba

# Config you should not change unless you know what you are doing
use-conda: True
use-apptainer: True
apptainer-args: "--bind $(pwd):$(pwd)"
