sample_table: "config/sample_metadata.csv" # Path to CSV table with columns: sample, group, strain, and more optional metadata.

fastqs:
  directory: "data/samples" # REVIEW # Path to directory with all FASTQ files 
  fastq_suffix1: "_1.fq.gz" # Everything after the sample name of the forward reads file.
  fastq_suffix2: "_2.fq.gz" # Everything after the sample name of the reverse reads file.

references: 
  directory: "data/references/" # REVIEW # Path to directory with reference genomes fastas (and GFFs if annotate_references activate is not set to True)

annotate_references:
  activate: True
  directory: "data/main_reference" # REVIEW # Path to directory with main reference genome and annotation
  gff: "FungiDB-65_CneoformansH99.gff" # Main reference gff. 
  fasta: "FungiDB-65_CneoformansH99_Genome.fasta" # Main reference fasta.
  liftoff:
    threads: 12
    extra: ""

coverage_quality: 
  activate: True
  mosdepth: 
    threads: 12
    window: 500
    min_mapq: 20
    extra: ""
  ploidy:
    smoothing_size: 15
    size: 5000
    change: 0.6
    repeats_database: "config/RepBase.fasta"
    repeats_threads: 36

plotting: 
  activate: True
  metadata2color : "isolation_source"

snippy:
  threads: 12
  extra: ""

liftoff:
  threads: 12
  extra: ""

agat:
  extra: ""

